name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qualsafedemo:$(date +%s)
    - name: Docker Tag
  # You may pin to the exact commit or the version.
  # uses: opspresso/action-docker@233ac522cc300320464ddd95cee4059986cc1587
    - uses: opspresso/action-docker@v0.4.0
    - run: docker --tag qualsafedemo:$(date +%s) qualsafedemo.jfrog.io/qualsafedemo:$(date +%s)
    - run: docker push qualsafedemo.jfrog.io/qualsafedemo:$(date +%s)
    
    
