# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build-Push-Deploy Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
  
  build-docker-image: 
  
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v3
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{ secrets.dockerhub_username }}
        DOCKER_PASSWORD: ${{ secrets.dockerhub_password }}
      run : docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" qualsafedemo.jfrog.io
      #run : echo $DOCKER_USERNAME
    - name: Build the Docker image
      #run: docker build myapp . --file Dockerfile --tag ${{secrets.docker_username}}/${{secrets.repo_name}}:${{steps.vars.outputs.tag}}
      run: docker build -t myapp .
    - name: Docker tag myapp 
      run: docker tag myapp qualsafedemo.jfrog.io/qualsafedemo-docker-local/myapp:${{steps.vars.outputs.tag}} 
    - name: Publish dockerimage to jfrog docker hub
      run: docker push qualsafedemo.jfrog.io/qualsafedemo-docker-local/myapp:${{steps.vars.outputs.tag}} 
  
